### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#121]
Currently we use MIT, but all other packages in mlr3 use LGPL3. I think this is probably an unnecessary inconsistency and the mlr3proba licence should be updated. Is this simply a case of changing it on Git or are there any implications for current code/docs/etc.?

I suspect @pat-s may know the most about this so your opinion is appreciated.

**Comment by pat-s** [comment]
Actually I am very weak when it comes to licenses. @mllg and @berndbischl know way more here.

**Comment by fkiraly** [comment]
As a potentially relevant point, LGPL is weak copyleft while MIT is permissive.

Depending on legal stance, some companies may have problems when it comes to using LGPL licensed software (or contributing to LGPL liensed software), while there are typically no problems whatsoever with permissive licenses such as MIT or BSD new/simplified versions.

I´m aware that LGPL is *weak* copyleft, as opposed to GPL which is (strong) copyleft, but it still may create problems for industrial usage (given certain legal environments). 
This may be a problem even if just "using" the package by install/load, since in some legale contexts this may already be automatically considered becoming "part of" the software/solution/tool that imports it, unless there is an intermediary (and technically completely unnecessary) step of data export/import is carried out.

So I would in general advise to pick MIT or BSD above LGPL, but obviously I'm biased in this respect with conflict of interest (and not a decision maker on this anyway).

Though in this specific case it does not matter much, since mlr3proba is still using mlr3 which is LGPL, and the use of mlr3proba requires use of mlr3. Thus, even if you only want to use mlr3proba only in a legal context that does not like LGPL, its use would be ultimately prevented by its dependency on mlr3.

**Comment by RaphaelS1** [comment]
> Actually I am very weak when it comes to licenses. @mllg and @berndbischl know way more here.

Ah sorry, thanks.

> Though in this specific case it does not matter much, since mlr3proba is still using mlr3 which is LGPL, and the use of mlr3proba requires use of mlr3. Thus, even if you only want to use mlr3proba only in a legal context that does not like LGPL, its use would be ultimately prevented by its dependency on mlr3.

This is my thinking too; LGPL overrides MIT so having proba on MIT is unnecessary and has no real effect, therefore should be changed for consistency.

**Comment by fkiraly** [comment]
>LGPL overrides MIT

I don´t think it does - you would just have different permissivities for different parts of mlr3.

**Comment by RaphaelS1** [comment]
> I don´t think it does - you would just have different permissivities for different parts of mlr3.

Which doesn't make sense practically as you require mlr3 to load any part of mlr3proba, same with paradox. By the time you strip all these out the proba code is useless, unusable, and uncopyable! Hence the MIT being pointless
