### ISSUE TITLE
Add visualisation to mlr3book

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#156]
Add pecs and plotting simulated predictions to round-off a complete workflow in mlr3book

**Comment by fkiraly** [comment]
"simulated predictions"? What do you mean with that, i.e., what is being simulated?
Don´t you simply just want to plot the actual predictions (the distributions) in a distr output type scenario?

**Comment by RaphaelS1** [comment]
> "simulated predictions"? What do you mean with that, i.e., what is being simulated?
> Don´t you simply just want to plot the actual predictions (the distributions) in a distr output type scenario?

Should have said 'possibly-simulated'. To visualise a fitted survival model otherwise you could plot actual predictions from a task of interest or pass a task with simulated data: https://github.com/mlr-org/mlr3proba/blob/master/R/plot.R

But yes essentially it does exactly what you say and uses the `distr6` plotting function to visualise distr predictions

**Comment by fkiraly** [comment]
Ah, so we´re just potentially using simulated data, but in either case the predictive distribution obtained from the distr output model is visualized. Makes sense.

Was just concerned since on occasion Bayesians insist on drawing samples from the predictive distribution, even if it is explicit (so no reason to draw from it if you want to inspect it).
