### ISSUE TITLE
Lacking error message "Assertion on 'self' failed" for wrong format of event variable  

### ISSUE THREAD

**Issue by tess-st** [mlr-org/mlr3proba#187]
I tried to tune a RF for my survival task. Therefore declared my event variable as factor variable. 
When I wanted to create the task up from this data the following error appeared: "_Error in .__TaskSurv__initialize(self = self, private = private, super = super,  : Assertion on 'c_ev' failed: Must be of type 'integerish', not 'factor'._".
When changing the event variable to integers which are not 0 and 1 (e.g. 1 and 2), the resampling fails with error "_Error: Assertion on 'self' failed. FALSE._", which does not indicate why something goes wrong.

```{r}
library(dplyr)
library(mlr3)
library(mlr3proba) # survival tasks, learners + measures
library(mlr3learners)
library(mlr3extralearners) #rfsrc

set.seed(220121)
task = tsk("rats")

# Integers 1 and 0
summary(task$data()$status)

install_learners("surv.rfsrc")
lrn_rfsrc = lrn("surv.rfsrc", ntree = 10L)

# resample works
resample(task = (task$clone())$filter(1:100), learner = lrn_rfsrc, resampling = rsmp("cv", folds = 2))

# change status to 1 and 2
data = task$data()
data$status = as.integer(as.factor(data$status))
summary(data$status)

task2 = TaskSurv$new(id = "rats2", backend = data %>% select(-"sex"),
  time = "time", event = "status", type = "right")

# resample fails
resample(task = (task2$clone())$filter(1:100), learner = lrn_rfsrc, resampling = rsmp("cv", folds = 2))
```
May you can print a warning beforehand or even allow (1,2) coding.

**Comment by RaphaelS1** [comment]
Though I agree the error message is poor, this is not a bug of proba but of `rfsrc`:

``` r
data = data.frame(x = rnorm(100), time = runif(100), status = sample(1:2, 100, T))
fit = randomForestSRC::rfsrc(formula = Surv(time, status) ~ x, data = data)
fit$family
#> [1] "surv-CR"
```

**Comment by tess-st** [comment]
thanks for claryfing this, should I add an issue in 'mlr3extralearners' for that or do you take care of it? The given error message was strongly misleading for me and I guess I won't be the last one stumbling on it, since afaik having the event variable formated as a factor is pretty common.
...and converting it led to my problem above

**Comment by RaphaelS1** [comment]
The bug is entirely in the {randomForestSRC} package, you could open an issue there if you like but there's not much we can do on our side. The problem is it wouldn't make sense for us to manually catch the bug in tha learner as we will be incorporating competing risks soon and therefore this will become desired behaviour so could get messy internally.

I've had problems myself with the `Surv` object and how it treats factors but also I've found in my experience people just tend to get use to using integers or logicals for censoring. i'm pretty sure we document this and reference original object but can't remember. Not sure how much more we can do from proba side
