### ISSUE TITLE
Parametric survival learner prediction `lp` = `crank`?

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3proba#306]
A small bug I spotted, see [here](https://github.com/mlr-org/mlr3extralearners/blob/main/R/learner_survival_surv_parametric.R#L144) - I guess the `lp` should stay as it is?

**Comment by RaphaelS1** [comment]
No it's fine here

**Comment by RaphaelS1** [comment]
And this is an open discussion. I still don't know best answer. The reason for the change is because everywhere else our survival learners have a different lp interpretation, hence modification here to bring it in line with other learners. But I agree we really only want `crank` to be the one we edit

**Comment by bblodfon** [comment]
hm, I see what you mean, I came across this in xgboost AFT [learner](https://github.com/mlr-org/mlr3extralearners/blob/main/R/learner_xgboost_surv_xgboost.R#L237) but it didn't prompt such thoughts to me at the time :)

So right now the convention is as follows: if a learner returns `lp` prediction always return it "PH-style" (higher value, higher risk) and `crank` follows `lp`.

Then, the discussion is to have `lp` exactly as it is returned from the respective learner (in terms of ordering) and change only `crank` appropriately (to be always in "PH-style")? But then this creates problems with scores that use `lp` and need it `PH-style` I guess (like some ROC-AUCs). Have you found a more elegant solution to tackle this in the Julia package?

**Comment by RaphaelS1** [comment]
> So right now the convention is as follows: if a learner returns lp prediction always return it "PH-style" (higher value, higher risk) and crank follows lp.

Exactly. Which to me still feels the safer option because most people will never think about this difference and it's very unlikely you'll be using mlr3proba for inference (therefore the subtlety matters less). Moreover, now I'm thinking about it again, it's important to be consistent for `lp` interpretation for the `distrcompositor` where you can choose between PH and AFT forms of models.

Currently for package we do same as in `survival` so PH and AFT are different (which they should be)
