### ISSUE TITLE
Time-dependent AUC

### ISSUE THREAD

**Issue by ahucephe** [mlr-org/mlr3proba#333]
I want to predict time-dependent AUC for surv.ranger learner. However, I couldn't achieve it with the mlr3proba package. First, I fit a model in mlr3proba. Then, I want to calculate the time-dependent AUC by the riskRegressin or survAUC packages. Because, in the mlr3proba package, the "Predict Types" for surv.ranger are “crank”, “distr”. I can't get "lp". How can I do that?

**Comment by RaphaelS1** [comment]
The response to your question is here https://github.com/mlr-org/mlr3proba/issues/332 -- you can't use survAUC for ranger as it doesn't make lp predictions

**Comment by ahucephe** [comment]
Isn't it correct to calculate time-dependent AUC for ranger? Why are there lp results for some learners but not for others?

**Comment by ahucephe** [comment]
I have one more question. Can I use exp(linear_pred)/(1+exp(linear_pred)) to convert the linear prediction value to survival probability? Similary, can I use log(surv.prob/1-surv.prob) for the opposite?

**Comment by RaphaelS1** [comment]
> Isn't it correct to calculate time-dependent AUC for ranger?

Yes but the issue is that the implementations all assume Cox regression is used to make the predictions, the exceptions to this are AUC.hc and AUC.uno but these also assume a one-to-one relationship between `lp` and the predicted survival probabilities, which won't hold for machine learning models

> Why are there lp results for some learners but not for others?

`lp` means linear predictor, it therefore can *only* apply to models that are fit with linear predictors, for example in the cox model: $h(t) = h_0(t)exp(x\beta)$ in this equation $x\beta$ is the linear predictor and $exp(x\beta)$ is commonly used for `crank` as a risk prediction.


>  Can I use exp(linear_pred)/(1+exp(linear_pred)) to convert the linear prediction value to survival probability? Similary, can I use log(surv.prob/1-surv.prob) for the opposite? So, is it lp=log(distr/1-distr) ?

`$distr` returns the *full* probability distribution over time so there any mapping from `linear_pred` to `distr` depends on the chosen model form, e.g. if using PH then `h(t) = h_0(t)exp(xb)` but it's different for accelerated failure time and proportional odds models.

**Comment by ahucephe** [comment]
So, how should I calculate time-dependent Auc after fitting a survival model (e.g. surv.ranger, surv.ctree) in mlr3proba that does not give lp results? Can you give me any suggestions on this issue?

**Comment by RaphaelS1** [comment]
> So, how should I calculate time-dependent Auc after fitting a survival model (e.g. surv.ranger, surv.ctree) in mlr3proba that does not give lp results?

You can't. mlr3proba was designed such that you can't make calculations that are mathematically wrong, the results wuld not be valid. You'd need to use antolini's C which is model-agnostic but I haven't implemented this yet - but you're welcome to help implement that if you have the time?

> And, can you give me the detailed calculation (or code) for surv.cindex measure for my comparisons?

I don't know what your code is so this is hard to do, which C-index are you using? Harrell's ?
