### ISSUE TITLE
Estimating crank if missing

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#36]
We agreed not to estimate the `distr` if not provided by the function natively, now we have a compositor to do this. But what about `crank` ?

By example `LearnerSurvRpart` can natively predict survival probabilities but has no return type for relative risk. So we could either derive this as the expectation of the survival distribution, or only return what is native to the function, `distr`, and add another compositor for estimation of `crank` from distr. This would look something like

```R
PipeOpCrankCompositor$new(id, param_set = ParamSet$new(params = list(
 ParamFct$new("method", levels = c("mean", "median"))
```
 Where the `method` would then be applied to the predicted `distr` to obtain a `crank`.

**Comment by fkiraly** [comment]
I'm still a bit hazy about how you would define `crank`.
Just *any* continuous ranking on predicted survival times? Which isn't uniquely specifying options.
In which case you could just return the survival times as `crank` - simply since any regression prediction is an implied continuous ranking of itself.

**Comment by RaphaelS1** [comment]
As discussed, we will add this compositor and open an issue for a final 'super' compositor for both `crank` and `distr`
