### ISSUE TITLE
param_vals inconsistent with mlr3

### ISSUE THREAD

**Issue by adibender** [mlr-org/mlr3proba#39]
https://github.com/mlr-org/mlr3book/pull/94 fails because `param_vals` was removed from **`mlr3`** in https://github.com/mlr-org/mlr3/pull/339, but still present in **`mlr3proba`**

**Comment by RaphaelS1** [comment]
That's strange, proba should be using the latest version of mlr3, clearly it isn't! Thanks I'll fix this shortly

**Comment by RaphaelS1** [comment]
The problem is in the `LearnerProbRegr` however I think this is going to be deleted and instead a `prob` response type will be added to `TaskRegr`. Similarly, whilst density is unfinished I was planning on commenting this out but had forgotten to do so. @mllg I noticed you added these tasks  in (1fd966f970281dec7c382d61f7fb97c1bd147134) but I think I might remove these and comment out the code which we won't be releasing in 0.1

**Comment by RaphaelS1** [comment]
passing now
