### ISSUE TITLE
Implementation of integrated scores

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#56]
For the mlr3proba that I'm writing I’ve collected all implementations of the integrated brier score and tested them all out on identical data. Surprisingly, all seem to be the same, with the unfortunate exception of mlr3proba. The reason for this is as follows:

mlr3proba approximates integration over time by just taking the sample mean over all time-points.

```R
mean(graf)
````

where Graf is the matrix of weighted scores over M time-points and N observations.

However, other packages weight the integral as follows. Using `ipred::sbrier` as an example (but `pec` is identical):

```
    idx <- 2:length(times)
    RET <- diff(times) %*% ((graf[idx - 1] + graf[idx])/2)
    RET <- RET/diff(range(times))
```

Where times are the unique survival times, Graf is the vector of scores over observations for each time-point.

I am wondering if we should:

1. Only use our method and naively take sample mean over time-points?
2. Use the `ipred` and `pec` method and weight by time-differences
3. Allow both options with an extra parameter called something like `int_method` and the user can choose the integration method.

The third option has the advantage of extra flexibility and will make it easier if we have other methods in the future.

@fkiraly

**Comment by fkiraly** [comment]
As far as I understand, the difference just lies in the choice of weighting function in the approximating integral (both approximating the w(x) = 1 weighted IBS/RPS which is a strictly proper loss):
(i) the Graf (1999) paper has a plug-in estimate for the inverse censoring distribution which is meant to cancel out the empirical weighting.
(ii) the `pec` et al suggestion has inverse bin width weights which are there to do the same.

These two options are not identical in a finite sample (only in asymptopia), and option (ii) seems like a cruder approximation to the analytic IBS/RPS since it re-weights by data point, as opposed to (i) where the cancellation happens at the level of the entire sample in the form of a plug-in estimate. Though of course a conclusive judgment on which approximation is "better" in which respect would require more careful theoretical analysis.

Generally, there seem to be multiple approximation ideas to the same loss (w=1 IBS/RPS) floating around (including my idea to not approximate at all if an analytic solution is available from `distr6`), so why not just implement all of them and keep track in the handbook, if it's not too much of a hassle.

**Comment by RaphaelS1** [comment]
>(ii) the pec et al suggestion has inverse bin width weights which are there to do the same.

This actually includes (i). So first average observations w.r.t. to censoring distribution then inverse bin width over time

> so why not just implement all of them and keep track in the handbook, if it's not too much of a hassle.

This is what I think I'll do

**Comment by fkiraly** [comment]
By the way, in addition, there are a bunch of other options where the weighting function is not w=1, analytical and approximate.

Graf (in her 1998 thesis) lists a few options including the "vanilla" one where no weighting term is introduced (effective weighting of the approximand being the censoring distribution).

**Comment by fkiraly** [comment]
>>(ii) the pec et al suggestion has inverse bin width weights which are there to do the same.

>This actually includes (i). 

I don't think so? I.e., I don't think (i) is a special case of (ii). The approximand is the same, but the approximation is different.
