### ISSUE TITLE
Abstraction of learners

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#99]
Subject to approval from the relevant people (I'm guessing @pat-s @mllg ?) it would be nice to abstract all learners and measures (#72) to mlr3learners and mlr3measures. We have 29 learners and counting, so could help to clean up the package a bit to core distributional prediction functionality.

**Comment by RaphaelS1** [comment]
Although `mlr3learners` says it's for "essential learners", so depends more on if you think any other learns should be stored in their own repo or just have one big repo for learners and one for measures..?

**Comment by pat-s** [comment]
> We have 29 learners and counting

ohh..wow! 

No learners are added into {mlr3learners} - all learners should go into https://github.com/mlr3learners following the https://github.com/mlr-org/mlr3learners.template.

**Comment by RaphaelS1** [comment]
Ah okay so just so I understand correctly there are three 'types' of learners:

1. Core learners, such as featureless and debug that live in `mlr3`
2. Essential learners that are commonly used in `classif` and `regr` which live in `mlr3learners`
3. Non-essential learners that users have to individually load from the `mlr3learners` org

In that case, I should classify each of my learners in a similar way. Would it be possible to have any essential survival/density learners in `mlr3learners` repo? I'm thinking only `surv.coxph`, `dens.kde`, `dens.hist`. If not I can keep these in `mlr3proba` along with `surv.kaplan` and `surv.nelson`

**Comment by pat-s** [comment]
> Ah okay so just so I understand correctly there are three 'types' of learners:

Exactly.

> Would it be possible to have any essential survival/density learners in mlr3learners repo?

We would have to discuss this. Putting three learners there would put a heavy weight on survival learners (3 out of 9 then) while survival learners are just a niche field in ML. Also giving this right to survival models would also give it to other fields then (e.g. forecasting) and this might blow up {mlr3learners} a lot.

> If not I can keep these in mlr3proba along with surv.kaplan and surv.nelson

In general we had the principle of not storing any learners in their extension packages but outsourcing such into their own small packages.
Extension packages like {mlr3proba} and others should just add the necessary infrastructure to mlr3 of the respective niche field they cover (in theory).

So in general I'd say that all learners should live in their own per-package repo in mlr3learners. If there is already one (because for example randomForest can handle survival inputs) then you can append the learner classes to this package.

**Comment by fkiraly** [comment]
would this be a bad point in time to bring up a potential proba return type for supervised regression? And the question where it should sit?

Survival I would agree is not core ML, but one might argue that probabilistic regression is kind of core - GP are for example a key model type.

**Comment by RaphaelS1** [comment]
Before we discuss that, see the issue I'm opening now

**Comment by mllg** [comment]
Some remarks:

* It is best to keep some basic learners and measures in proba, otherwise testing your package is impossible.

* Having some learners in mlr3learners would require mlr3learners to depend on mlr3proba (or moving the base classes to mlr3). We need to discuss this.

* I'd suggest keeping the measures in mlr3proba. If you write some measures yourself though, it would be nice to put a standalone version into mlr3measures. This way everybody can use them without having to install mlr3.

**Comment by RaphaelS1** [comment]
Survival learners to keep here

* `coxph, kaplan`

Density learners to keep:

* `histogram, kde`

Survival learners to move:

* [ ] Blackboost
* [ ] Coxboost
* [ ] CVCoxboost
* [ ] CVGlmnet
* [ ] Flexible
* [ ] Gamboost
* [ ] GBM
* [ ] Glmboost
* [ ] Glmnet
* [ ] Mboost
* [ ] Nelson
* [ ] ObliqueRSF
* [ ] Parametric
* [ ] Penalized
* [ ] RandomForestSRC
* [ ] Ranger
* [ ] Rpart
* [ ] SVM
* [ ] XGBoost

Density learners to move:

* [ ] KDEkd
* [ ] KDEks
* [ ] Locfit
* [ ] Logspline
* [ ] Mixed
* [ ] Nonparametric
* [ ] Penalized
* [ ] Plugin
* [ ] Spline

**Comment by adibender** [comment]
I guess for at least obliqueRSF we need to create `mlr3learners.obliqueRSF`. I could do that or maybe contact the maintainer if he is willing to do that.

**Comment by RaphaelS1** [comment]
I'm going to edit the above now to include packages and whether they currently exist in the repo or not, should make it easier to decide how to act going forward...

**Comment by RaphaelS1** [comment]
@adibender the maintainer of what? If `mlr3learners.obliqueRSF` doesn't already exist then there's no maintainer right?

**Comment by adibender** [comment]
> @adibender the maintainer of what? If `mlr3learners.obliqueRSF` doesn't already exist then there's no maintainer right?

sorry, not precise enough. I meant the maintainer of obliqueRSF, maybe he would be interested to maintain the integration with mlr3 himself...

**Comment by RaphaelS1** [comment]
Hm...I think that may get even riskier then if we leave maintenance of learners we implemented to someone outside mlr if they didn't implement it themselves? Unless you know them of course

**Comment by adibender** [comment]
I can do it myself as well.

**Comment by adibender** [comment]
`rpart` lives in **`mlr3`**, so `surv.part` should go there? `xgboost` and `ranger` live in **`mlr3learners`**,

**Comment by RaphaelS1** [comment]
> `rpart` lives in **`mlr3`**, so `surv.part` should go there? `xgboost` and `ranger` live in **`mlr3learners`**,

I have no idea... @pat-s ?

**Comment by pat-s** [comment]
> rpart lives in mlr3, so surv.part should go there? xgboost and ranger live in mlr3learners,

I'd say so, yes.

**Comment by pat-s** [comment]
> sorry, not precise enough. I meant the maintainer of obliqueRSF, maybe he would be interested to maintain the integration with mlr3 himself, i.e., create mlr3learners.obliqueRSF and maintain it. 

You can at least ask and give him permissions. Whether he will do something then is up to him :) But this is up to you of course. We won't be very strict with permissions in the mlr3learners org.

**Comment by RaphaelS1** [comment]
> I'd say so, yes.

But then we would have to also add `LearnerSurv` to `mlr3` or depend on `mlr3proba`, which is definitely not a good idea... Might just be easier to keep `surv.rpart` in `mlr3proba`?

**Comment by pat-s** [comment]
> But then we would have to also add LearnerSurv to mlr3 or depend on mlr3proba, which is definitely not a good idea... Might just be easier to keep surv.rpart in mlr3proba?

Maybe it would be ok if its in "Suggests" only? 
Having it in mlr3proba even though the rest of rpart lives in mlr3 would be another special case then that would not follow the heuristics of all other mlr3learners.
In the end @mllg needs to decide this.

The same goes for mlr3learners - here I would also suggest to add mlr3proba so "Suggests"  only because not everyone who installs mlr3learners needs it.
And the policy is anyhow that installing mlr3learners does not install the upstream packages, only if the user sets `dependencies = TRUE`.

**Comment by adibender** [comment]
> > But then we would have to also add LearnerSurv to mlr3 or depend on mlr3proba, which is definitely not a good idea... Might just be easier to keep surv.rpart in mlr3proba?
> 
> Maybe it would be ok if its in "Suggests" only?
> Having it in mlr3proba even though the rest of rpart lives in mlr3 would be another special case then that would not follow the heuristics of all other mlr3learners.
> In the end @mllg needs to decide this.
> 
> The same goes for mlr3learners - here I would also suggest to add mlr3proba so "Suggests" only because not everyone who installs mlr3learners needs it.
> And our policy is anyhow that installing mlr3learners does not install the upstream packages, only if the user sets `dependencies = TRUE`.

The problem I see here is that in the future more "proba" like packages could emerge, e.g., when proba ist split up into survival and density, spatial stuff, time-series, image-recognition/DL, NLP... 
All of a sudden you have a host of suggests in mlr3. Some of these extensions might not even be from our group. They would have to put their `LearnerNLPrpart` object into core mlr3 and their package added to suggests...

**Comment by fkiraly** [comment]
I think a relevant idea to consider might be a registry, e.g., in a dedicated repository, that deals with all tasks considered non-standard. 
MLJ.jl has one for learners and their tags, one could easily extend that architecture to have learners and learning tasks as relational categories in the registry.

For probabilistic regression, one could make the case for inclusion in core though, since deterministic/probabilistic classification and deterministic regression on tabular (i.i.d.) data are already considered core, so in the imaginary 2 x 2 table one field is missing.

That may just amount to a special return type `distr` for the regression task (I would also like to see interval there).

Survival is more specialized so I can see this sitting outside core.
